### ISSUE TITLE
Find a way how to avoid accumulating all batches with Lightning

### ISSUE THREAD

**Issue by DaloroAT** [OML-Team/open-metric-learning#118]
PL accumulate all outputs from train and val during epoch

Then you can call 

```
    def training_epoch_end(self, outputs: EPOCH_OUTPUT) -> None:
        ...

    def validation_epoch_end(self, outputs: EPOCH_OUTPUT) -> None:
        ...
```

**Comment by AlekseySh** [comment]
Hey, @DaloroAT 

Seems like a false alarm here. It stores only loss values. 

I added the code that you mentioned above to the `ExtractorModule`:

```python
    def training_epoch_end(self, outputs):
        print(outputs, "yyy")
```

And the output was:

```
[{'loss': tensor(0.3917)}, {'loss': tensor(0.)}] yyy
```

So, nothing that we need to fight with.
