### ISSUE TITLE
Visualise 2-d embedding space for TripletLoss and for ArcFace for some simple dataset like MNIST

### ISSUE THREAD

**Issue by AlekseySh** [OML-Team/open-metric-learning#128]
There are several purposes:

1 - understand how these losses behave in comparison with each other
2 - understand what's going on if we combine them
3 - we can write a short post on Medium about it to attract new people to OML

**Comment by churnikov** [comment]
Hi!

Can I work on this issue after we finish this one https://github.com/OML-Team/open-metric-learning/issues/85 ?
