### ISSUE TITLE
add pre-commit to check that readme was built correctly 

### ISSUE THREAD

**Issue by AlekseySh** [OML-Team/open-metric-learning#162]
https://pre-commit.com/#new-hooks

**Comment by b0nce** [comment]
May be useful: https://dev.to/jalvaradosegura/create-your-own-pre-commit-hook-3kh

**Comment by AlekseySh** [comment]
I realized we need to create a stand-alone repo and make a python package to add a custom pre-commit. Seems like too much effort for such a small check. So, I am closing the issue.
