### ISSUE TITLE
Use configs from dataclasses and not from .yaml files.

### ISSUE THREAD

**Issue by b0nce** [OML-Team/open-metric-learning#190]
It turns out that one can use [config groups and dataclasses](https://hydra.cc/docs/1.2/tutorials/structured_config/config_groups/) for defaults in hydra. Code will look much cleaner, and we also could access configs just from python code with imports [here](https://github.com/OML-Team/open-metric-learning/blob/9a55d4b581f052b6ea8ce91c4a05e5959e1e2c7d/oml/lightning/entrypoints/train.py#L182), [here](https://github.com/OML-Team/open-metric-learning/blob/9a55d4b581f052b6ea8ce91c4a05e5959e1e2c7d/tests/test_oml/test_registry/test_registry.py#L50), [here](https://github.com/OML-Team/open-metric-learning/blob/9a55d4b581f052b6ea8ce91c4a05e5959e1e2c7d/tests/test_oml/test_transforms/test_image_augs.py#L16) and in many more places.
![image](https://user-images.githubusercontent.com/27873390/196374338-9051e5b4-5d8a-421a-bd05-28397f2c9619.png)
![image](https://user-images.githubusercontent.com/27873390/196374426-047dfa68-ffd5-45fd-a651-a24db83a1578.png)

**Comment by b0nce** [comment]
I see the only reason to keep configs: users will know how to parameterize things they add in configs.

**Comment by AlekseySh** [comment]
Let's postpone it for now.
