### ISSUE TITLE
Add links to default .yaml configs in documentation

### ISSUE THREAD

**Issue by b0nce** [OML-Team/open-metric-learning#213]
At the moment, we have no appropriate documentation for config API.
We've discussed with @AlekseySh that there are two possible ways to fix it:
 - Make a test which will force you to add a link to .yaml for each class. As a result, we want to have a "config" button similar to "source" for every class.
 - Make a table for default configs [here](https://open-metric-learning.readthedocs.io/en/latest/examples/config.html).

**Comment by AlekseySh** [comment]
It's kind of solved after the documentation for Pipelines has been introduced
https://github.com/OML-Team/open-metric-learning/tree/main/pipelines/features_extraction#customization
