### ISSUE TITLE
Introduce a test to check code examples in functions' doc strings 

### ISSUE THREAD

**Issue by AlekseySh** [OML-Team/open-metric-learning#241]
We introduced some code examples in doc strings for our functions. For example, here: 

https://github.com/OML-Team/open-metric-learning/blob/main/oml/functional/metrics.py#L237 

https://github.com/OML-Team/open-metric-learning/blob/main/oml/functional/metrics.py#L314 

https://github.com/OML-Team/open-metric-learning/blob/main/oml/functional/metrics.py#L380 

https://github.com/OML-Team/open-metric-learning/blob/main/oml/functional/metrics.py#L461

**Comment by AlekseySh** [comment]
The start of the discussion was here: https://github.com/OML-Team/open-metric-learning/issues/240#issuecomment-1328211431

**Comment by AlekseySh** [comment]
@Illumaria Hey! Seems like you like working on infrastructure issues. Do you want to work on this one?

PS. Anyway, let us know if you want to contribute to the repo again, and we will find something suitable for you :)

**Comment by Illumaria** [comment]
> @Illumaria Hey! Seems like you like working on infrastructure issues. Do you want to work on this one?
> 
> PS. Anyway, let us know if you want to contribute to the repo again, and we will find something suitable for you :)

Hi! Sure, I'd like to keep contributing, but with respect to real-life issues. 😅

As for this task, do I get it correctly that all that you want is to simply run examples from docstrings during tests? In other words, is [this](https://github.com/OML-Team/open-metric-learning/pull/254) what you need?

**Comment by AlekseySh** [comment]
@Illumaria Sure, no pressure at all :) 
Let's continue the discussion in PR

**Comment by AlekseySh** [comment]
https://github.com/OML-Team/open-metric-learning/pull/254 - link to pr

**Comment by AlekseySh** [comment]
Hey, @Illumaria, just a polite reminder :) If you don't have time now, it's okay, the task isn't urgent
