### ISSUE TITLE
Optimise calculation of distances matrix

### ISSUE THREAD

**Issue by AlekseySh** [OML-Team/open-metric-learning#243]
We may need a lot of RAM during metrics calculation since we need to compute distances matrix:
https://github.com/OML-Team/open-metric-learning/blob/main/oml/functional/metrics.py#L201
For example, we need more than 20 GB for Stanford Online Products dataset.

We cannot do anything with the size of the matrix itself, but probably we may find a way to reduce the memory footprint needed for the intermediate calculation.

**Comment by dapladoc** [comment]
One possible solution is to evaluate the distance matrix row by row (or batch-of-rows by batch-of-rows), and update metrics, that support such regime. For instance, cmc, percision, map could work in such way, fnmr@fmr can't. But if accumulate histograms of positive and negative distances, then fnmr@fmr could be approximated.

**Comment by AlekseySh** [comment]
It's a valid point. I don't know whether functionality like this is available from the box or with minimal effort using some 3d party solutions

**Comment by AlekseySh** [comment]
duplicate: https://github.com/OML-Team/open-metric-learning/issues/283
