### ISSUE TITLE
Decrease memory foot print of computing FMR metric 

### ISSUE THREAD

**Issue by AlekseySh** [OML-Team/open-metric-learning#251]
Initial discussion is in https://github.com/OML-Team/open-metric-learning/pull/250

**Comment by AlekseySh** [comment]
from @dapladoc :

> I thought about some algorithm to find quantiles online, in a batch mode. I found that there is P^2 algorithm [(link)](https://www.cse.wustl.edu/~jain/papers/ftp/psqr.pdf) and here is a discussion about it [(link)](https://stats.stackexchange.com/questions/7959/algorithm-to-dynamically-monitor-quantiles).
Then I found more articles about quantile estimation: see references to this article [(link)](https://oda.oslomet.no/oda-xmlui/bitstream/handle/10642/7943/Quantile_Multiplicative_Cybernetics.pdf?sequence=1). It looks like all these algorithms work only element-by-element. So, no way to parallelize it. I'm not a specialist in this, though.
Maybe it could be done effectively in cython. I'll try to implement the P^2 (or some other algorithm) in cython.

Another solution is to approximate the quantile (and the fnmr@fmr) by means of histogram, that could be computed incrementally. I can try to estimate accuracy of this approach on some syntetic data.

At the moment I don't have other ideas, but I will think on it, and maybe something new will come up.

**Comment by AlekseySh** [comment]
from me:

> @dapladoc thank you for your thoughts and links! please, don't start working on cython implementation (except if you really want this), let's discuss it for now. I am afraid that the possible profit is way less than the potential effort needed to implement this algorithm. Let's just discuss possibilities for now.

> I like the idea of an approximation. I thought about an even simpler solution: we can consider only the part of pairwise distances if the matrix is too big. For example, randomly pick 10% or something like this.

>  It's still unclear what is the problem: the footprint of copying distances or memory overhead inside the quantile algorithm.

**Comment by AlekseySh** [comment]
The graphs above seem okay to me, it's I consider fnmr@fmr only as an additional (auxiliary) metric. So, it's not super important 30% or 32% of positive distances are smaller than 10% of the negative ones.
Of course, If I submit these results somewhere, it's not accurate enough.

**Comment by AlekseySh** [comment]
If we want to work on this problem systematically, we have to measure the following first (for example, on SOP dataset):
1. Memory is needed to compute 3 basic metrics (CMC, precision, ap)
2. Memory is needed to do p.1 + copy the positive and negative distances
3. Memory is needed to do p.2 + compute fnm@fmr metric 

Then it would be clear what and how should be optimized 

PS. My IMHO is that we can postpone the problem for now (https://github.com/OML-Team/open-metric-learning/pull/250 is enough) and focus on the tasks with higher priorities. In the end, it's probably not optimal to optimize fmr metric without (at least) having examples from the verification domain.

**Comment by dapladoc** [comment]
> The graphs above seem okay to me, it's I consider fnmr@fmr only as an additional (auxiliary) metric. So, it's not super important 30% or 32% of positive distances are smaller than 10% of the negative ones. Of course, If I submit these results somewhere, it's not accurate enough.

It really depends on the domain. For security related tasks (i.e. biometrics) 99.9% and 99.99% are noticebly different results.



> PS. My IMHO is that we can postpone the problem for now (#250 is enough) and focus on the tasks with higher priorities. In the end, it's probably not optimal to optimize fmr metric without (at least) having examples from the verification domain.

I agree with you. There should be more thorough memory measurements done in order to find possible ways to solve this issue.

**Comment by AlekseySh** [comment]
A bit optimizer it along with OML 3.0 release (removed unwilling convertations):
https://github.com/OML-Team/open-metric-learning/blob/main/oml/functional/metrics.py#L375
