### ISSUE TITLE
Add a test for PairwisePostprocessor

### ISSUE THREAD

**Issue by AlekseySh** [OML-Team/open-metric-learning#270]
Add a test that automatically checks that `PairwisePostprocessor@top_n` cannot change `precision@k` and `cmc@k` if `k > top_n`

**Comment by Natyren** [comment]
Hello @AlekseySh! Can you tell in more detail what is required and where it is necessary to implement it in the code?

**Comment by AlekseySh** [comment]
Hi, @Natyren!
I appreciate your interest. 

First, take a look at the existing tests: https://github.com/OML-Team/open-metric-learning/tree/main/tests/test_oml/test_postprocessor 

The idea is to add there a test that checks that `PairwisePostprocessor@top_n` cannot change `precision@k` and `cmc@k` if `k > top_n`. So, it may be performed on some randomly generated data.

**Comment by AlekseySh** [comment]
@Natyren Could you also take a look at this issue: https://github.com/OML-Team/open-metric-learning/issues/283. It's very localised, so it may be great as a first issue. And it also has high priority for us.

**Comment by Natyren** [comment]
@AlekseySh I took a look, and will try to work on it

**Comment by AlekseySh** [comment]
@Natyren great!

**Comment by Natyren** [comment]
Since #283  has moved to the revue stage, I'm starting to work on this issue

**Comment by AlekseySh** [comment]
@Natyren you are welcome. I hope you have all the needed information

**Comment by AlekseySh** [comment]
This issue is available again for anyone who wants to work on it :)
