### ISSUE TITLE
torch._C._LinAlgError: linalg.svd: The algorithm failed to converge

### ISSUE THREAD

**Issue by PapaMadeleine2022** [OML-Team/open-metric-learning#335]
Hello, I have a problem. I use resnet50 as backbone, and I want to remove the original `fc` layer (2048x1000 size) and add a new embedding fc (2048 x256 size), So in the `oml/models/resnet.py` I change the code:
```
self.model.fc = nn.Identity()
```
to:
```
self.model.fc = nn.Linear(2048, 256)
```
Then, I train CUB 200 dataset by `train_cub.py`.
But when it comes to `Validation` after training `Epoch14`, it shows error:
```
  File "/xxx/open-metric-learning-main/oml/functional/metrics.py", line 536, in calc_pcf
    pca = PCA(embeddings)
  File "/xxx/open-metric-learning-main/oml/utils/misc_torch.py", line 346, in __init__
    self._fit(embeddings)
  File "/xxx/open-metric-learning-main/oml/utils/misc_torch.py", line 363, in _fit
    _, self.singular_values, self.components = torch.linalg.svd(embeddings, full_matrices=full_matrices)
torch._C._LinAlgError: linalg.svd: The algorithm failed to converge because the input matrix is ill-conditioned or has too many repeated singular values (error code: 14).

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

```

What causes this error? Can you give some advises?
Looking forward your reply.
Thanks very much~

**Comment by AlekseySh** [comment]
Hi, generally changing the source code of the repo is not a good practice. You can install OML from pip and then use it via imports. The examples folder is not a part of the repo, so, you should copy the needed example and it will work using OML via imports.  

If you want to use your custom model, I recommend you inherit it from `IExtractor` and implement it yourself. Then you can pass it to Config-API following the simple instruction (it shows your exact case): https://open-metric-learning.readthedocs.io/en/latest/examples/config.html#how-to-use-my-own-implementation-of-loss-model-augmentations-etc

**Comment by PapaMadeleine2022** [comment]
as you suggest, I use:

```
class CustomModel(IExtractor):

    def __init__(self, pretrained):
        super().__init__()
        self.resnet = resnet50(pretrained=pretrained)
        self.resnet.fc =  nn.Linear(2048, 256)
        
    def forward(self, x):
        self.resnet(x)
```
Then I train CUB 200 dataset by `train_cub.py`, but it shows error:
```
...
    step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File "/conda/envs/oml-py3.7/lib/python3.7/site-packages/pytorch_lightning/strategies/strategy.py", line 193, in optimizer_step
    return self.precision_plugin.optimizer_step(model, optimizer, opt_idx, closure, **kwargs)
  File "/conda/envs/oml-py3.7/lib/python3.7/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 155, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
  File "/conda/envs/oml-py3.7/lib/python3.7/site-packages/torch/optim/optimizer.py", line 140, in wrapper
    out = func(*args, **kwargs)
  File "/conda/envs/oml-py3.7/lib/python3.7/site-packages/torch/optim/optimizer.py", line 23, in _use_grad
    ret = func(self, *args, **kwargs)
  File "/conda/envs/oml-py3.7/lib/python3.7/site-packages/torch/optim/adam.py", line 183, in step
    loss = closure()
  File "/conda/envs/oml-py3.7/lib/python3.7/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 140, in _wrap_closure
    closure_result = closure()
  File "/conda/envs/oml-py3.7/lib/python3.7/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 148, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/conda/envs/oml-py3.7/lib/python3.7/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 134, in closure
    step_output = self._step_fn()
  File "/conda/envs/oml-py3.7/lib/python3.7/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 427, in _training_step
    training_step_output = self.trainer._call_strategy_hook("training_step", *step_kwargs.values())
  File "/conda/envs/oml-py3.7/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1765, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/conda/envs/oml-py3.7/lib/python3.7/site-packages/pytorch_lightning/strategies/strategy.py", line 333, in training_step
    return self.model.training_step(*args, **kwargs)
  File "/conda/envs/oml-py3.7/lib/python3.7/site-packages/oml/lightning/modules/retrieval.py", line 78, in training_step
    bs = len(embeddings)
TypeError: object of type 'NoneType' has no len()
```

**Comment by AlekseySh** [comment]
First, you need to implement `feat_dim`
Second, could you show your `train_cub.py`?

**Comment by PapaMadeleine2022** [comment]
First:
How to implement `feat_dim` ?
Second:
```
import hydra
import torchvision.transforms as t
from omegaconf import DictConfig
from torchvision.models import resnet18, resnet50

from oml.interfaces.models import IExtractor
from oml.lightning.entrypoints.train import pl_train
from oml.registry.models import EXTRACTORS_REGISTRY
from oml.registry.transforms import TRANSFORMS_REGISTRY
from oml.models.pooling import GEM
from torch import nn

class CustomModel(IExtractor):

    def __init__(self, pretrained):
        super().__init__()
        self.resnet = resnet50(pretrained=pretrained)
        self.resnet.fc =  nn.Linear(2048, 256)
        
    def forward(self, x):
        self.resnet(x)

    @property
    def feat_dim(self):
        return self.resnet.fc.out_features


def get_custom_augs() -> t.Compose:
    return t.Compose([
        t.RandomHorizontalFlip(),
        t.RandomGrayscale(),
        t.ToTensor(),
        t.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ])


TRANSFORMS_REGISTRY["custom_augmentations"] = get_custom_augs
EXTRACTORS_REGISTRY["custom_model"] = CustomModel


@hydra.main(config_path=".", config_name="train_cub.yaml")
def main_hydra(cfg: DictConfig) -> None:
    pl_train(cfg)


if __name__ == "__main__":
    main_hydra()
```

**Comment by PapaMadeleine2022** [comment]
> as you suggest, I use:
> 
> ```
> class CustomModel(IExtractor):
> 
>     def __init__(self, pretrained):
>         super().__init__()
>         self.resnet = resnet50(pretrained=pretrained)
>         self.resnet.fc =  nn.Linear(2048, 256)
>         
>     def forward(self, x):
>         self.resnet(x)
> ```
> 
> Then I train CUB 200 dataset by `train_cub.py`, but it shows error:
> 
> ```
> ...
>     step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
>   File "/conda/envs/oml-py3.7/lib/python3.7/site-packages/pytorch_lightning/strategies/strategy.py", line 193, in optimizer_step
>     return self.precision_plugin.optimizer_step(model, optimizer, opt_idx, closure, **kwargs)
>   File "/conda/envs/oml-py3.7/lib/python3.7/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 155, in optimizer_step
>     return optimizer.step(closure=closure, **kwargs)
>   File "/conda/envs/oml-py3.7/lib/python3.7/site-packages/torch/optim/optimizer.py", line 140, in wrapper
>     out = func(*args, **kwargs)
>   File "/conda/envs/oml-py3.7/lib/python3.7/site-packages/torch/optim/optimizer.py", line 23, in _use_grad
>     ret = func(self, *args, **kwargs)
>   File "/conda/envs/oml-py3.7/lib/python3.7/site-packages/torch/optim/adam.py", line 183, in step
>     loss = closure()
>   File "/conda/envs/oml-py3.7/lib/python3.7/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 140, in _wrap_closure
>     closure_result = closure()
>   File "/conda/envs/oml-py3.7/lib/python3.7/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 148, in __call__
>     self._result = self.closure(*args, **kwargs)
>   File "/conda/envs/oml-py3.7/lib/python3.7/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 134, in closure
>     step_output = self._step_fn()
>   File "/conda/envs/oml-py3.7/lib/python3.7/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 427, in _training_step
>     training_step_output = self.trainer._call_strategy_hook("training_step", *step_kwargs.values())
>   File "/conda/envs/oml-py3.7/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1765, in _call_strategy_hook
>     output = fn(*args, **kwargs)
>   File "/conda/envs/oml-py3.7/lib/python3.7/site-packages/pytorch_lightning/strategies/strategy.py", line 333, in training_step
>     return self.model.training_step(*args, **kwargs)
>   File "/conda/envs/oml-py3.7/lib/python3.7/site-packages/oml/lightning/modules/retrieval.py", line 78, in training_step
>     bs = len(embeddings)
> TypeError: object of type 'NoneType' has no len()
> ```

it seems that you miss the `return` of  `self.resnet(x)`  in  function `forward(self, x)` in [https://open-metric-learning.readthedocs.io/en/latest/examples/config.html#how-to-use-my-own-implementation-of-loss-model-augmentations-etc](url)

**Comment by AlekseySh** [comment]
@PapaMadeleine2022 you are right! thank you, I missed `return`

Does it work if you put it back?

**Comment by AlekseySh** [comment]
@PapaMadeleine2022 `feat_dim` has to return the output size of your vectors. It's 256 in your case.

It will be used in the validation stage to allocate memory for your embeddings. So, normally it should crash during the validation if there is no `feat_dim` property. 

Please, note, that validation starts at every N-th epoch, where N is specified in the config: https://github.com/OML-Team/open-metric-learning/blob/main/examples/extractor_cub/train_cub.yaml#L34

**Comment by PapaMadeleine2022** [comment]
> Hello, I have a problem. I use resnet50 as backbone, and I want to remove the original `fc` layer (2048x1000 size) and add a new embedding fc (2048 x256 size), So in the `oml/models/resnet.py` I change the code:
> 
> ```
> self.model.fc = nn.Identity()
> ```
> 
> to:
> 
> ```
> self.model.fc = nn.Linear(2048, 256)
> ```
> 
> Then, I train CUB 200 dataset by `train_cub.py`. But when it comes to `Validation` after training `Epoch14`, it shows error:
> 
> ```
>   File "/xxx/open-metric-learning-main/oml/functional/metrics.py", line 536, in calc_pcf
>     pca = PCA(embeddings)
>   File "/xxx/open-metric-learning-main/oml/utils/misc_torch.py", line 346, in __init__
>     self._fit(embeddings)
>   File "/xxx/open-metric-learning-main/oml/utils/misc_torch.py", line 363, in _fit
>     _, self.singular_values, self.components = torch.linalg.svd(embeddings, full_matrices=full_matrices)
> torch._C._LinAlgError: linalg.svd: The algorithm failed to converge because the input matrix is ill-conditioned or has too many repeated singular values (error code: 14).
> 
> Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
> ```
> 
> What causes this error? Can you give some advises? Looking forward your reply. Thanks very much~

when I use `GEM` and resentv2 rather v1 like this:

```
    def __init__(self, pretrained):
        super().__init__()
        # self.resnet = resnet50(pretrained=pretrained)
        self.resnet = resnet50(weights=ResNet50_Weights.IMAGENET1K_V2)
        self.resnet.avgpool = GEM(p=5.0)
        self.resnet.fc =  nn.Linear(2048, 256)
```
it would not show above error.

**Comment by AlekseySh** [comment]
1) I have not tested it with v2. Does it work for v1? If does, you need to dive deeper to realize the problem, because, on OML's side, we cannot support all the possible combinations of backbone architectures. From OML point of view, the model just has to be a child of `IExtractor`

2) Yes, you have implemented it

**Comment by PapaMadeleine2022** [comment]
> 



> 1. I have not tested it with v2. Does it work for v1? If does, you need to dive deeper to realize the problem, because, on OML's side, we cannot support all the possible combinations of backbone architectures. From OML point of view, the model just has to be a child of `IExtractor`
> 2. Yes, you have implemented it

1.It works for v1 only when p=3.0. If I change p to 5.0 or 7.0, it will shows above error.
2.Ok, got it!

**Comment by AlekseySh** [comment]
1. I have an assumption that for higher values of `p` in GeM produced vectors are too similar and a matrix cannot be decomposed. It's just a guess.
