### ISSUE TITLE
Inference script

### ISSUE THREAD

**Issue by PapaMadeleine2022** [OML-Team/open-metric-learning#337]
Hello, I already  train my model and get weights. But how to infer an image to get  the last embedding. Can you provide a script?

**Comment by AlekseySh** [comment]
Hey, sure! There is a script in `Readme -> Get started using Python -> Using a trained model for retrieval`.

**Comment by AlekseySh** [comment]
For an example on one image you can check [this](https://github.com/OML-Team/open-metric-learning#how-to-use-models-from-zoo).

**Comment by AlekseySh** [comment]
There is no direct connection between training transforms (augmentations) and testing transforms. **And they definitely must be different**. They have different natures, as I explained before in another issue. It's not an OML-specific thing, but a general rule. 

Answering your question. Yes, you can use these transforms, in this case, you will have the following:
* `get_augs_albu` - your train augs (https://github.com/OML-Team/open-metric-learning/blob/165d63b93cd8da5d1fc52ae7b4a95bbd026fb164/oml/transforms/images/albumentations.py#L106) 
* `get_normalisation_resize_albu` - your test transforms

**Comment by AlekseySh** [comment]
PS. you may be also interested in another example of model usage: `Using a trained model for retrieval` (in Readme)

**Comment by PapaMadeleine2022** [comment]
> PS. you may be also interested in another example of model usage: `Using a trained model for retrieval` (in Readme)

ok, thanks
