### ISSUE TITLE
need more detailed doc about postprocess

### ISSUE THREAD

**Issue by PapaMadeleine2022** [OML-Team/open-metric-learning#353]
Hello, I read the `postprocessing` 's [readme](https://github.com/OML-Team/open-metric-learning/tree/main/pipelines/postprocessing/pairwise_postprocessing#readme) . But I still do not know the function of this operation. Can you provide more detailed doc about it ?

**Comment by AlekseySh** [comment]
It's a valid point. I'm working on documentation right now. I started with a readme for feature extraction (in a separate branch), and then I will cover postprocessing.

We will also publish a preprint on Arxiv soon, which describes the method and motivation.

**Comment by PapaMadeleine2022** [comment]
looking forward to it.

Besides, can you provide the details of `improvement` with `postprocessing ` vs without `postprocessing `

**Comment by AlekseySh** [comment]
It was 
86.5 -> 88.2 on SOP
92.1 -> 94.9 on InShop

**Comment by PapaMadeleine2022** [comment]
> It was 86.5 -> 88.2 on SOP 92.1 -> 94.9 on InShop

niice

**Comment by AlekseySh** [comment]
@PapaMadeleine2022 check it out! We released preprint of paper and demo 
https://github.com/OML-Team/open-metric-learning/tree/main/pipelines/postprocessing/pairwise_postprocessing

**Comment by PapaMadeleine2022** [comment]
> @PapaMadeleine2022 check it out! We released preprint of paper and demo https://github.com/OML-Team/open-metric-learning/tree/main/pipelines/postprocessing/pairwise_postprocessing

nice~
