### ISSUE TITLE
Handling multilabel classification

### ISSUE THREAD

**Issue by nmohr192** [OML-Team/open-metric-learning#357]
Hey,

I have a multilabel classification problem I'd like to solve using distance metric learning. For runtime evaluation of OOD samples and "weird" images, going with a distance metric learning based classifier backbone is favorable to me, so I can tell whether a new sample is far off my cluster centroids per class.
The issue is, that I have a multilabel classification problem, as multiple relevant objects can be in an image. How would you handle this currently? Do i just add another row for the same filename in the data.csv file but with the other class label assigned?
Or do I just leave ambiguous labels out of the training?

Thanks

EDIT:

I noticed, that in your example CSVs provided in the documentation (https://open-metric-learning.readthedocs.io/en/latest/oml/data.html), there is one CSV `df_sop.csv` which contains a new column "super_class_id" which is not documented anywhere. Did you write a custom dataset and sampler for that? I can't find any reference to it in your documentation.

**Comment by AlekseySh** [comment]
Hey,

If your image has 3 objects on it, I recommend you to have 3 different rows in `df.csv` with the corresponding bounding boxes

**Comment by AlekseySh** [comment]
`super_class_id` is a legacy thing, it's just an enum for the category column.
Thank you for pointing this out, I will remove it from the examples :)

**Comment by nmohr192** [comment]
> Hey,
> 
> If your image has 3 objects on it, I recommend you to have 3 different rows in `df.csv` with the corresponding bounding boxes

Unfortunately, the objects are also overlapping or intersecting most of the time. What is your recommendation?

1. leave out ambiguous examples with intersecting / overlapping examples
2. do as you proposed and still keep 2 rows for the same image if its multilabel

**Comment by nmohr192** [comment]
> By the way
> 
> > The issue is, that I have a multilabel classification problem, as multiple relevant objects can be in an image.
> 
> It's an object detection problem. "multilabel classification problem" means that you have an image of a car and it has few labels: "car", "red", "4-wheels"

It's not in my case. Yes, there are objects and I also have bounding box labels but I do not care about coordinates of objects in an image in my scenario. I just want to know whether certain things are present in an image, without caring for where exactly they are present.

**Comment by AlekseySh** [comment]
Got it.
