### ISSUE TITLE
How to infer images on multi gpu?

### ISSUE THREAD

**Issue by PapaMadeleine2022** [OML-Team/open-metric-learning#374]
Hello, I want to infer an amount of images and get the last embedding of each image. 
Now I use `inference_on_images ` function like:
```
args = {"num_workers": 0, "batch_size": 8}
features_queries = inference_on_images(extractor, paths=queries, transform=transform, **args)
```
But it seems to run only on cpu. I modify oml's code in `ckpt = torch.load(weights, map_location="cpu")` [here](https://github.com/OML-Team/open-metric-learning/blob/main/oml/models/vit/vit.py#L127) to `ckpt = torch.load(weights, map_location="cuda:0"})`

Then I run `inference_on_images`, but the `Memory-Usage` on GPU does not increase, and the `GPU-Util` is still zero.
So how to successfully infer images on gpu and multi gpu to get the last embedding of each image?

**Comment by AlekseySh** [comment]
@PapaMadeleine2022 Hey, you can do it even more simpler with `validate_cub.py`. Just go to the metric callback and take the accumulator from that, it stores all the available information. It would be something like `metric_callback.metric.acc.storage`.

PS. Ideally, we need a dedicated script for inference.

**Comment by PapaMadeleine2022** [comment]
> 

For question 1, can you give some advises ?

**Comment by AlekseySh** [comment]
Move your model to gpu
`model.to(...)`

**Comment by PapaMadeleine2022** [comment]
> @PapaMadeleine2022 Hey, you can do it even more simpler with `validate_cub.py`. Just go to the metric callback and take the accumulator from that, it stores all the available information. It would be something like `metric_callback.metric.acc.storage`.
> 
> PS. Ideally, we need a dedicated script for inference.

Still do not understand how to do it. Can you give some examples?

**Comment by AlekseySh** [comment]
@PapaMadeleine2022 , For example, in this notebook:
https://github.com/OML-Team/open-metric-learning/blob/main/pipelines/features_extraction/visualization.ipynb

We did validation, then we took the callback. See `clb_metric.metric`. 
If you go to `clb_metric.metric.acc.storage` you access all the data that was accumulated during the validation.

**Comment by PapaMadeleine2022** [comment]
> accumulated

If I can only access all the data that was accumulated during the validation.it seems not to fit my needs. Because my val data is hug, such that memory will not be able to store all the images.

**Comment by AlekseySh** [comment]
it doesn't accumulate images, only embeddings, paths, bboxes, labels...

**Comment by PapaMadeleine2022** [comment]
> embeddings
Sorry, I had a wrong expression. I have fixed my above words.

**Comment by AlekseySh** [comment]
You can easily calculate the required space, usually, embeddings are light enough. 

If you cannot put them into the memory, you can dump them to a file or/and decrease the embedding size and retrain the model or/and use PCA (implemented by your own).
