### ISSUE TITLE
Fastest method

### ISSUE THREAD

**Issue by VladimirYugay** [OML-Team/open-metric-learning#376]
Are the methods in the Zoo are suitable for real-time applications? 

If yes, what is the fastest method present at OML?

**Comment by AlekseySh** [comment]
@VladimirYugay, real-time can mean different things depending on your application. 

As for Zoo, there are ResNets and ViTs. The first ones are faster.

You can pick MoCo pretrained checkpoint (Self-Supervised method):
`ResnetExtractor.from_pretrained("resnet50_moco_v2")` (only `resnet50` is available)
or a model trained as a vanilla classifier on ImageNet:
`ResnetExtractor.from_pretrained("resnet50_imagenet1k_v1")` (all ResNets are available, including the fastest one -- `resnet18`)
