### ISSUE TITLE
How to infer images after trainig a  postprocessor?

### ISSUE THREAD

**Issue by IamMegatron2025** [OML-Team/open-metric-learning#385]
Hello, I use `pipelines/postprocessing/pairwise_postprocessing/postprocessor_train.yaml` to train my model. Then how to infer images using this trained `postprocessor` model ? Can you provide some examples?

**Comment by PapaMadeleine2022** [comment]
Need help ~

**Comment by AlekseySh** [comment]
Hey, @PapaMadeleine2022 !

There is no stand-alone example yet, but I will prepare one for you soon.

**Comment by AlekseySh** [comment]
@PapaMadeleine2022 

I've added an example for you. It will be [here](https://open-metric-learning.readthedocs.io/en/latest/postprocessing/python_examples.html) in a few minutes, right after the new docs will be built. 

If you are interested in customising your postprocessing, I can recommend you take a loot at this [repo](https://github.com/nastygorodi/PROJECT-Deep_Metric_Learning). It's a good example of customising OML's logic of postprocessing, in particular, it implements multi-query postprocessing in two ways: simple frequency-based heuristic and using a neural network.

**Comment by PapaMadeleine2022** [comment]
> @PapaMadeleine2022
> 
> I've added an example for you. It will be [here](https://open-metric-learning.readthedocs.io/en/latest/postprocessing/python_examples.html) in a few minutes, right after the new docs will be built.
> 
> If you are interested in customising your postprocessing, I can recommend you take a loot at this [repo](https://github.com/nastygorodi/PROJECT-Deep_Metric_Learning). It's a good example of customising OML's logic of postprocessing, in particular, it implements multi-query postprocessing in two ways: simple frequency-based heuristic and using a neural network.

Thanks very much~
