### ISSUE TITLE
TensorBoardLogger data shape error and suggestions for image path checking.

### ISSUE THREAD

**Issue by FD-Liekkas** [OML-Team/open-metric-learning#387]
Thank you very much for creating such an excellent package! It has greatly facilitated my exploration in the field of metric learning！

**TensorBoardLogger data shape error**
[https://github.com/OML-Team/open-metric-learning/blob/main/oml/lightning/callbacks/metric.py](url), line 108. I think it should be changed to`pl_module.logger.experiment.add_image(log_str, np.transpose(data, (2, 0, 1)), pl_module.current_epoch)`
Because line 107 give a shape of [HWC], and tensorboard received shapes of [CHW], [HWC], [HW] refer to [https://tensorboardx.readthedocs.io/en/latest/tensorboard.html#tensorboardX.SummaryWriter.add_image](url). It will cause image to be horizontally flipped if we use `pl_module.logger.experiment.add_image(log_str, np.swapaxes(data, 0, 2), pl_module.current_epoch)`

**suggestions for image path checking**
[https://github.com/OML-Team/open-metric-learning/blob/main/oml/utils/dataframe_format.py](url), line 73.
It is used to check if image path exist in dataset dataframe. Will cost too much time to run this line if we have a big dataset trained in DDP mode. I suggest add a parameter to control this line execution.

**Comment by FD-Liekkas** [comment]
> 

My dataset has 400k images, it cost me more than 4h to cross this line in DDP mode. Maybe line 73 is not an efficient way. But when I run this line Individually out of DDP mode, it come over less than 30min, wired actually.

**Comment by FD-Liekkas** [comment]
> PS. I kindly ask you to keep one issue only for one topic, then it's easier to maintain. Thanks!

It's actually rare for me to submit issues on GitHub, so I'm sorry about that. I'll be more mindful next time, haha.

**Comment by FD-Liekkas** [comment]
> My dataset has 400k images, it cost me more than 4h to cross this line in DDP mode. Maybe line 73 is not an efficient way. But when I run this line Individually out of DDP mode, it come over less than 30min, wired actually.
So I run this line before starting my train pipeline and add a `check_path_exists` parameter to this func so I can go around this line. GPU time is expensive after all 😂.

**Comment by FD-Liekkas** [comment]
> My dataset has 400k images, it cost me more than 4h to cross this line in DDP mode. Maybe line 73 is not an efficient way. But when I run this line Individually out of DDP mode, it come over less than 30min, wired actually.

So I run this line before starting my train pipeline and add a check_path_exists parameter to this func so I can go around this line. GPU time is expensive after all 😂.

**Comment by AlekseySh** [comment]
@FD-Liekkas Thank you for the details! Seems like we probably need to do something.

What particular pipeline are you talking about? Is it a feature extractor training pipeline or do you train a postprocessor?

**Comment by AlekseySh** [comment]
@FD-Liekkas Got it!

Could you kindly make a PR introducing the flag mentioned above?
Here is contributing guide: https://open-metric-learning.readthedocs.io/en/latest/oml/contributing.html
