### ISSUE TITLE
Support LoRA for training to obtain a larger batch size for a larger extractor

### ISSUE THREAD

**Issue by FD-Liekkas** [OML-Team/open-metric-learning#397]
It requires a large amount of GPU memory when training a big Vision Transformer model like ViT-B/8 DINO. The biggest portion of memory consumption may come from the activations saved in the forward pass, especially with a larger batch size. However, we need more negative samples in a batch for comparison during optimization. It would be great to introduce LoRA (Low-Rank Adaptation of Large Language Models) into ViT backbone.

**Comment by AlekseySh** [comment]
Hey, @FD-Liekkas! Thank you for using OML.

You are right, LoRA may be a cool feature for the library. @b0nce has some experience with LoRA, probably, we discussed it offline, so he can make the corresponding contribution. If so, @b0nce, could you provide a small snippet of code which shows your approach? You can start by modifying the train example.

**Comment by AlekseySh** [comment]
Close due to inactivity
