### ISSUE TITLE
Example: export a model to onnx

### ISSUE THREAD

**Issue by Fissium** [OML-Team/open-metric-learning#399]
Hi! Are you planning to provide a tool for exporting to various formats, for example, onnx?

**Comment by AlekseySh** [comment]
Hi, @Fissium! Thank you for using OML!

Our models can be converted to ONNX by existing tools since they are not really special. In some of the [examples](https://open-metric-learning.readthedocs.io/en/latest/feature_extraction/python_examples.html#) we also use PyTorch Lightning, which has the functionality of converting models to ONNX. You also use it as well.

If you will find a convenient and straightforward way of converting models, don't hesitate to add this code snippet to our examples :) I will help in case of any problems

**Comment by DaloroAT** [comment]
Pytorch has built-in capabilities for converting models to ONNX

https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html

**Comment by AlekseySh** [comment]
@DaloroAT , thank you!

**Comment by AlekseySh** [comment]
I would loke to close this issue for now, because seems like converting to ONNX is not special for OML models

**Comment by AlekseySh** [comment]
After all, probably we need to have the example.

**Comment by Fissium** [comment]
@AlekseySh Here is the example https://github.com/Fissium/metric-learning/blob/main/examples/vit_to_onnx.py

If that's what we need, I'll add it to the documentation.

**Comment by AlekseySh** [comment]
@Fissium yes, it's what we need :)
Before you started adding that to the documentation, could you also check if this approach works for other architectures? 

As for the documentation. What do you think is the best format?
- One more example under expander in Readme like for validation or training (+link to colab? not sure about it, because it's painful to keep all of them up to date)
- Separate page in Readthedocs?
- other options?

**Comment by Fissium** [comment]
@AlekseySh Yes, I'll check if this approach works for other architectures. 

As for the format, it depends on the number of such examples that aren't directly related to oml. But I'd create a separate page in readthedocs.

**Comment by AlekseySh** [comment]
@Fissium hm.. as far as we build readthedocs from the pieces of readme, we can have this example in both places automatically

**Comment by Fissium** [comment]
@AlekseySh

- Experiment [link](https://colab.research.google.com/drive/1sjmHBmwAHY5Qq8pxD5QA2UdVTKmr1Aaz?usp=sharing)

**Results**

|Extractor|Arch|Export Support|Error|
|---|---|---|---|
|ViTExtractor|vits8|Yes|None|
|ViTExtractor|vits16|Yes|None|
|ViTExtractor|vitb8|Yes|None|
|ViTExtractor|vitb16|Yes|None|
|ViTExtractor|vits14|Yes|None|
|ViTExtractor|vitb14|Yes|None|
|ViTExtractor|vitl14|Yes|None|
|ViTExtractor|vits14_reg|No|Exporting the operator 'aten::_upsample_bicubic2d_aa' to ONNX opset version 17 is not supported|
|ViTExtractor|vitb14_reg|No|Exporting the operator 'aten::_upsample_bicubic2d_aa' to ONNX opset version 17 is not supported|
|ViTExtractor|vitl14_reg|No|Exporting the operator 'aten::_upsample_bicubic2d_aa' to ONNX opset version 17 is not supported|
|ViTUnicomExtractor|vitb32_unicom|No|_Map_base::at|
|ViTUnicomExtractor|vitb16_unicom|No|_Map_base::at|
|ViTUnicomExtractor|vitl14_unicom|No|_Map_base::at|
|ViTUnicomExtractor|vitl14_336px_unicom|No|_Map_base::at|
|ViTCLIPExtractor|vitb16_224|Yes|None|
|ViTCLIPExtractor|vitb32_224|Yes|None|
|ViTCLIPExtractor|vitl14_224|Yes|None|
|ViTCLIPExtractor|vitl14_336|No|The size of tensor a (577) must match the size of tensor b (257) at non-singleton dimension 1|
|ResnetExtractor|resnet18|Yes|None|
|ResnetExtractor|resnet34|Yes|None|
|ResnetExtractor|resnet50|Yes|None|
|ResnetExtractor|resnet50_projector|Yes|None|
|ResnetExtractor|resnet101|Yes|None|
|ResnetExtractor|resnet152|Yes|None|

- Bug in `ViTCLIPExtractor("vitl14_336")`, causing inference error.
- `ViTUnicomExtractor` is not exportable.
- `dinov2` with registers is not yet supported.

**Comment by AlekseySh** [comment]
@Fissium thank you very much for the information! I will think how to proceed...

**Comment by AlekseySh** [comment]
@Fissium Sorry for the late response.

I think we can create a short snippet of code under this example: https://github.com/OML-Team/open-metric-learning?tab=readme-ov-file#how-to-use-models-from-zoo. It should be really short and contain code for exporting one model to ONNX.

Ideally, we should also add this snippet to the tests here: https://github.com/OML-Team/open-metric-learning/blob/104023514868b3eb85f232ca5cd805881c6297e8/tests/test_runs/test_code_from_markdown.py#L40, but after that we also need to add ONNX to the test (or optional) dependencies. But I'm not sure it worth it... Generally speaking, OML has nothing to do with ONNX, but people were asking...

As for your experiments, we can post a link nearby that test to a separate page on readthedocs where we put your table above. 


What do u think?

**Comment by Fissium** [comment]
@AlekseySh You're right. OML has nothing to do with ONNX. What if we create an additional section in the FAQ and just mention this issue there? So we can put an example right here.

**Comment by AlekseySh** [comment]
@Fissium hm, okay, let's do this way. I think it would be better if we create a new issue and post your results and comments in the first message

**Comment by AlekseySh** [comment]
@Fissium Hi, let's finish here :)

**Comment by AlekseySh** [comment]
@Fissium ping :)

**Comment by AlekseySh** [comment]
Done here: https://github.com/OML-Team/open-metric-learning/issues/592
