### ISSUE TITLE
I can't pip install 

### ISSUE THREAD

**Issue by duckheada** [OML-Team/open-metric-learning#444]
**Hardware**: apple macbook pro 2023 M2 chip

**Steps to reproduce:**
On a colab notebook:

`!pip install -U open-metric-learning
`

**Output:**

ERROR: Cannot install open-metric-learning==0.3.0, open-metric-learning==0.3.1, open-metric-learning==0.3.10, open-metric-learning==0.3.11, open-metric-learning==0.3.12, open-metric-learning==0.3.13, open-metric-learning==0.3.14, open-metric-learning==0.3.2, open-metric-learning==0.3.3, open-metric-learning==0.3.4, open-metric-learning==0.3.5, open-metric-learning==0.3.6, open-metric-learning==0.3.7, open-metric-learning==0.3.8, open-metric-learning==0.3.9, open-metric-learning==0.4.0, open-metric-learning==0.4.1, open-metric-learning==0.4.2, open-metric-learning==0.4.3, open-metric-learning==0.4.4, open-metric-learning==0.4.5 and open-metric-learning==0.4.6 because these package versions have conflicting dependencies.

The conflict is caused by:
    open-metric-learning 0.4.6 depends on torch<=1.13.0 and >=1.10
    open-metric-learning 0.4.5 depends on torch<=1.13.0 and >=1.10
    open-metric-learning 0.4.4 depends on torch<=1.13.0 and >=1.10
    open-metric-learning 0.4.3 depends on torch<=1.13.0 and >=1.10
    open-metric-learning 0.4.2 depends on torch<=1.13.0 and >=1.10
    open-metric-learning 0.4.1 depends on torch<=1.13.0 and >=1.10
    open-metric-learning 0.4.0 depends on torch<=1.13.0 and >=1.10
    open-metric-learning 0.3.14 depends on torch<=1.13.0 and >=1.10
    open-metric-learning 0.3.13 depends on torch<=1.13.0 and >=1.10
    open-metric-learning 0.3.12 depends on torch<=1.13.0 and >=1.10
    open-metric-learning 0.3.11 depends on torch<=1.13.0 and >=1.10
    open-metric-learning 0.3.10 depends on torch<=1.13.0 and >=1.10
    open-metric-learning 0.3.9 depends on torch<=1.13.0 and >=1.10
    open-metric-learning 0.3.8 depends on torch<=1.13.0 and >=1.10.*
    open-metric-learning 0.3.7 depends on torch<=1.13.0 and >=1.10.*
    open-metric-learning 0.3.6 depends on numpy==1.21.6
    open-metric-learning 0.3.5 depends on numpy==1.21.6
    open-metric-learning 0.3.4 depends on numpy==1.21.6
    open-metric-learning 0.3.3 depends on numpy==1.21.6
    open-metric-learning 0.3.2 depends on numpy==1.21.6
    open-metric-learning 0.3.1 depends on numpy==1.21.6
    open-metric-learning 0.3.0 depends on numpy==1.21.6

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by AlekseySh** [comment]
Okay, let's see what is going on!

I've created an empty env with conda and installed OML without a problem (it's MacOS, but it's an intel chip). The Python version was 3.8.

Can you try to install the library in a new environment? (What was your python version?) 
```
 conda create -n test python==3.8 
 ```

**Comment by duckheada** [comment]
solved it by running:

`!!pip install -U open-metric-learning 
`
on my notebook.

**Comment by AlekseySh** [comment]
@duckheada nice to here, I'm closing the issue then
