### ISSUE TITLE
how to train a custom ImageFolder dataset

### ISSUE THREAD

**Issue by Wzj02200059** [OML-Team/open-metric-learning#450]
Thank you for your awesome work! I'm interesting and wana try to training on my own ImageFolder dataset.
i first convert my dataset to SOP  or INSHOP format and then convert it to df format.
but i failed, and the offical  tiny dataset also can not pass check_retrieval_dataframe_format.
so is there some scripts can easily convert ImageFolder dataset to df format.
Thanks a lot

**Comment by AlekseySh** [comment]
Hey! Thank you for using OML, @Wzj02200059. 

I'll take a look at why our tiny dataset (you talk about figures dataset, right?) cannot pass the check. It's weird.

A few questions for you:
* Could you show the resulting df you got? 
* What error does the check function show?
* What if you ignore the check function and try to run the training script?

**Comment by Wzj02200059** [comment]
Hi！@AlekseySh 
Thanks for your reply! You are totally right. I used your code and successfully passed the check.
And I wrote a script to convert my data to SOP format，also finished the training sucessfully.
Now I'm really expecting the results of the experiment! 
Haha, hope it can be better than convnext + triplet plan  I used before.
Thank you very much !
Best Regards

**Comment by AlekseySh** [comment]
@Wzj02200059 Thank you for using OML!

Feel free to report the experiment results or describe your setup in more detail, because it also helps me to understand real use cases.
