### ISSUE TITLE
Consider for upgrade numpy version from 1.23 to last? / Support Python 3.11

### ISSUE THREAD

**Issue by dimka11** [OML-Team/open-metric-learning#453]
Can't install OML with Python 3.11.6 because can't build numpy version 1.23 from source.

**Comment by AlekseySh** [comment]
Hey, @dimka11 and thank you for using OML!

I will take a look & check what we can do in the coming days. Until then, could you use it with a lower python version?

**Comment by AlekseySh** [comment]
The needed changes are here: https://github.com/OML-Team/open-metric-learning/pull/461

**Comment by AlekseySh** [comment]
@dimka11  and @brianlow It's done! Thank you for raising this issue.

If it works not as expected, please, let me know.

**Comment by AlekseySh** [comment]
update: the thing with NumPy is solved, but still working on fully supporting python 3.11
after I fully test it, I will publish new OML version in PIP

**Comment by AlekseySh** [comment]
It should work fine now
