### ISSUE TITLE
ddp training script in doc not work

### ISSUE THREAD

**Issue by Wzj02200059** [OML-Team/open-metric-learning#456]
i wanna train a Unicom Extractor, and i use  the example ddp trianing script in doc [Training + Validation [Lightning Distributed]
but return TypeError: __init__() got an unexpected keyword argument 'use_distributed_sampler'
so i delete the use_distributed_sampler, make ddp_args = {"accelerator": "gpu", "devices": 2, "strategy": DDPStrategy()}  
but still return error: AttributeError: 'DDPSamplerWrapper' object has no attribute 'batch_size'.

**Comment by Wzj02200059** [comment]
and my oml version is 0.4.6
my train code is :
import pytorch_lightning as pl
import torch
import pandas as pd
from pathlib import Path
from oml.datasets.base import DatasetQueryGallery, DatasetWithLabels
from oml.losses.triplet import TripletLossWithMiner
from oml.miners.inbatch_all_tri import AllTripletsMiner
from oml.models import ViTUnicomExtractor
from oml.samplers.balance import BalanceSampler
from oml.lightning.modules.extractor import ExtractorModuleDDP
from oml.lightning.callbacks.metric import MetricValCallbackDDP
from oml.metrics.embeddings import EmbeddingMetricsDDP
from pytorch_lightning.strategies import DDPStrategy

csv_path = 'dataset/sj/train.csv'
dataset_root = 'images/'
df = pd.read_csv(Path(csv_path))
df_train = df[df["split"] == "train"].reset_index(drop=True)
df_val = df[df["split"] == "validation"].reset_index(drop=True)

extractor = ViTUnicomExtractor.from_pretrained("vitb16_unicom")
from oml.registry.transforms import get_transforms_for_pretrained
transforms, im_reader = get_transforms_for_pretrained("vitb16_unicom")

# train
optimizer = torch.optim.SGD(extractor.parameters(), lr=1e-6)
train_dataset = DatasetWithLabels(df_train, dataset_root=dataset_root)
criterion = TripletLossWithMiner(margin=0.1, miner=AllTripletsMiner())
batch_sampler = BalanceSampler(train_dataset.get_labels(), n_labels=2, n_instances=3)
train_loader = torch.utils.data.DataLoader(train_dataset, batch_sampler=batch_sampler)

val_dataset = DatasetQueryGallery(df_val, dataset_root=dataset_root)
val_loader = torch.utils.data.DataLoader(val_dataset, batch_size=4)
metric_callback = MetricValCallbackDDP(metric=EmbeddingMetricsDDP())  # DDP specific

pl_model = ExtractorModuleDDP(extractor=extractor, criterion=criterion, optimizer=optimizer,
                              loaders_train=train_loader, loaders_val=val_loader  # DDP specific
                              )
ddp_args = {"accelerator": "gpu", "devices": 2, "strategy": DDPStrategy()}  # DDP specific
trainer = pl.Trainer(max_epochs=1, callbacks=[metric_callback], num_sanity_val_steps=0, **ddp_args)
trainer.fit(pl_model)  # we don't pass loaders to .fit() in DDP

**Comment by Wzj02200059** [comment]
my oml version is 0.4.6
# my training code is :
import pytorch_lightning as pl
import torch
import pandas as pd
from pathlib import Path
from oml.datasets.base import DatasetQueryGallery, DatasetWithLabels
from oml.losses.triplet import TripletLossWithMiner
from oml.miners.inbatch_all_tri import AllTripletsMiner
from oml.models import ViTUnicomExtractor
from oml.samplers.balance import BalanceSampler
from oml.lightning.modules.extractor import ExtractorModuleDDP
from oml.lightning.callbacks.metric import MetricValCallbackDDP
from oml.metrics.embeddings import EmbeddingMetricsDDP
from pytorch_lightning.strategies import DDPStrategy

csv_path = 'dataset/sj/train.csv'
dataset_root = 'images/'
df = pd.read_csv(Path(csv_path))
df_train = df[df["split"] == "train"].reset_index(drop=True)
df_val = df[df["split"] == "validation"].reset_index(drop=True)

extractor = ViTUnicomExtractor.from_pretrained("vitb16_unicom")
from oml.registry.transforms import get_transforms_for_pretrained
transforms, im_reader = get_transforms_for_pretrained("vitb16_unicom")

optimizer = torch.optim.SGD(extractor.parameters(), lr=1e-6)
train_dataset = DatasetWithLabels(df_train, dataset_root=dataset_root)
criterion = TripletLossWithMiner(margin=0.1, miner=AllTripletsMiner())
batch_sampler = BalanceSampler(train_dataset.get_labels(), n_labels=2, n_instances=3)
train_loader = torch.utils.data.DataLoader(train_dataset, batch_sampler=batch_sampler)

val_dataset = DatasetQueryGallery(df_val, dataset_root=dataset_root)
val_loader = torch.utils.data.DataLoader(val_dataset, batch_size=4)
metric_callback = MetricValCallbackDDP(metric=EmbeddingMetricsDDP())  # DDP specific

pl_model = ExtractorModuleDDP(extractor=extractor, criterion=criterion, optimizer=optimizer,
                              loaders_train=train_loader, loaders_val=val_loader  # DDP specific
                              )
ddp_args = {"accelerator": "gpu", "devices": 2, "strategy": DDPStrategy()}  # DDP specific
trainer = pl.Trainer(max_epochs=1, callbacks=[metric_callback], num_sanity_val_steps=0, **ddp_args)
trainer.fit(pl_model)  # we don't pass loaders to .fit() in DDP

**Comment by Wzj02200059** [comment]
and i try to modify yaml extractor parm to:
  extractor:
    name: vit_unicom
    args:
      normalise_features: True
      weights: vitb16_unicom
      arch: vitb16_unicom
  
it shows error:
  RuntimeError: Expected to mark a variable ready only once. 

if i want to use vit_unicom backbone, what additional changes do I need to make,  on the basic of official train_sop.yaml？

**Comment by Wzj02200059** [comment]
and i try to modify yaml extractor  parm to:
  extractor:
    name: vit_unicom
    args:
      normalise_features: True
      weights: vitb16_unicom
      arch: vitb16_unicom
  
it shows error:
  RuntimeError: Expected to mark a variable ready only once. 

if i want to use vit_unicom backbone, what additional changes do I need to make,  on the basic of official train_sop.yaml？

**Comment by AlekseySh** [comment]
Hey, @Wzj02200059 

Most likely the problem is that we updated OML to the 2.0 version (so it works with PyTroch >= 2.0 and Lightning >= 2.0). So, the documentation and example configs are for OML 2.0

Do you have any restrictions that don't allow you to update your OML?

**Comment by Wzj02200059** [comment]
> Hey, @Wzj02200059
> 
> Most likely the problem is that we updated OML to the 2.0 version (so it works with PyTroch >= 2.0 and Lightning >= 2.0). So, the documentation and example configs are for OML 2.0
> 
> Do you have any restrictions that don't allow you to update your OML?

The problen is resolved after updated. thanks for your reply.

**Comment by AlekseySh** [comment]
You are welcome and thank you for using OML, @Wzj02200059!
