### ISSUE TITLE
Ideas for experiments 

### ISSUE THREAD

**Issue by AlekseySh** [OML-Team/open-metric-learning#46]
- smaller emb size
- AdamW
- different architectures (not only vits8)
- gradually increasing margin 
- track statistic for hard combinations of labels or categories and during the next epoch sample them with the higher change 
- try some normalisation trick in triplet loss https://quaterion.qdrant.tech/tutorials/triplet_loss_trick.html

**Comment by b0nce** [comment]
Gradualy increasing margin forward epoch number to triplet loss
Use formula for margin:
`margin = max_margin * sigmoid(epoch_number + log(min_margin / (max_margin - min_margin)))`
