### ISSUE TITLE
Clarifying difference with text embedding models in FAQ

### ISSUE THREAD

**Issue by ogencoglu** [OML-Team/open-metric-learning#484]
Thanks for the great work!

With the popularity of LLMs and Retrieval Augmented Generation (RAG), probably many newcomers will encounter your library as it mentions embeddings. Would be probably beneficial to have another answer to FAQ clarifying if this library can perform text embeddings. If so, what is the difference of the methodologies w.r.t. all the embedders in the [MTEB leaderboard](https://huggingface.co/spaces/mteb/leaderboard).

**Comment by AlekseySh** [comment]
Hi, @ogencoglu! 

The answer is yes and no. There are a number of people I know who used OML to train their own text embedders on their data. They reworked `Dataset` and the rest remained the same (metrics, sampling, triplet loss). But I don't have this functionality as examples or tutorials at the moment, but I'm planning to cover it.

Thank you for your questions. I'm still thinking about the better way of doing it.

**Comment by AlekseySh** [comment]
I will also update FAQ
