### ISSUE TITLE
unicom model inference problem

### ISSUE THREAD

**Issue by Wzj02200059** [OML-Team/open-metric-learning#490]
i can not use unicom model to inference.
my inference code is :
model = ViTUnicomExtractor.from_pretrained("vitb16_unicom")
transforms, im_reader = get_transforms_for_pretrained("vitb16_unicom")
img = im_reader("2.jpg") 
img_tensor = transforms(img)
features = model(img_tensor.unsqueeze(0))

but it show ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 768])
and my version is:
Pillow                    10.0.1
torch                     2.0.0+cu117
torchvision               0.15.0+cu117
open-metric-learning      2.0.0
opencv-python             4.8.1.78

**Comment by Wzj02200059** [comment]
Problem was sloved.
The reason is i forgot write "model.eval()" ....

**Comment by AlekseySh** [comment]
@Wzj02200059 hi! thank you for using OML :) Feel free to provide any other feedback

**Comment by AlekseySh** [comment]
By the way, @Wzj02200059, please, check your e-mail. I have something to ask you.
