### ISSUE TITLE
How to specify pretrained model ?

### ISSUE THREAD

**Issue by PapaMadeleine2022** [OML-Team/open-metric-learning#494]
Hello, how to specify pretrained model in train_cub.yaml ?

**Comment by AlekseySh** [comment]
Hi, @PapaMadeleine2022, nice to see you here again :) 

The provided config is already [using](https://github.com/OML-Team/open-metric-learning/blob/main/pipelines/features_extraction/extractor_cub/train_cub.yaml#L55) pretrained model of general purpose -- DINO

More models [here](https://github.com/OML-Team/open-metric-learning/tree/main/oml/configs/extractor) and [here](https://github.com/OML-Team/open-metric-learning/tree/main?tab=readme-ov-file#zoo).

**Comment by PapaMadeleine2022** [comment]
I mean how to specify a local weights path.  I have done it. Modifying only the `weights` config path in  `train_cub.yaml` is ok.

**Comment by AlekseySh** [comment]
yep, that's right

you can check training and validation configs on CARS example, where I left a lot of comments regarding every part of the configs
