### ISSUE TITLE
The figures in the introduction of  `handling-sequences-of-photos` are too small

### ISSUE THREAD

**Issue by PapaMadeleine2022** [OML-Team/open-metric-learning#497]
Hello, the two [figures](https://open-metric-learning.readthedocs.io/en/latest/feature_extraction/python_examples.html#handling-sequences-of-photos) you provided are too small. Can you update them with higher resolution？

**Comment by AlekseySh** [comment]
hey @PapaMadeleine2022 

hm, they look bit enough on my computer
here are the direct links:
[one](https://i.ibb.co/Q6zwdfZ/tigers1.png)
[two](https://i.ibb.co/FbHBfzb/tigers2.png)

**Comment by AlekseySh** [comment]
They are 640x360 now. If I make them bigger, it will increase time needed for the page loading

**Comment by PapaMadeleine2022** [comment]
> hey @PapaMadeleine2022
> 
> hm, they look bit enough on my computer here are the direct links: [one](https://i.ibb.co/Q6zwdfZ/tigers1.png) [two](https://i.ibb.co/FbHBfzb/tigers2.png)

nice
