### ISSUE TITLE
Support of non-arm platforms in docker images

### ISSUE THREAD

**Issue by nik123** [OML-Team/open-metric-learning#498]
I'm unable to run an image on my LInux desktop. When I run the following commands:

```
docker pull omlteam/oml:gpu
docker run -it --rm omlteam/oml:gpu bash
```

I get the following error:
```
WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64/v4) and no specific platform was requested
exec /bin/sh: exec format error
```

It seems that only arm64 architecture is supported in the images. Are there any plans for amd64 support?

**Comment by AlekseySh** [comment]
@nik123 Hey, recommend you clone the repo, go to the [Makefile](https://github.com/OML-Team/open-metric-learning/blob/main/Makefile) and build docker by yourself on your machine: there is a command `docker_build`.

**Comment by nik123** [comment]
Thank you, @AlekseySh! I'll give it a shot. Nonetheless, it seems a bit odd that the amd64 architecture isn't available in any of the official docker images. Are there any plans to include support for the amd64 platform in the future?

**Comment by AlekseySh** [comment]
@nik123 I don't have an amd64 machine & capacity for this task at the moment. But if you want to contribute, you are welcome! :)

**Comment by nik123** [comment]
> But if you want to contribute, you are welcome! 

@AlekseySh I think it's possible to implement via Github CI/CD. I'll fork the repository and will try to write a proper pipeline

**Comment by AlekseySh** [comment]
@nik123 I think the result should be a command in Makefile that builds docker for the platform you need + Dockerfile. I don't want to put this into CI/CD in order not to spent its time everytime we run it. I will manually upload the new docker image to dockerhub from time to time (I do the same now for the current docker).

**Comment by AlekseySh** [comment]
due to inactivity
