### ISSUE TITLE
Add DINO v2 to ZOO

### ISSUE THREAD

**Issue by AlekseySh** [OML-Team/open-metric-learning#505]
Dino v2: https://github.com/facebookresearch/dinov2

[Contribution instruction](https://github.com/OML-Team/open-metric-learning/blob/main/CONTRIBUTING.md#contributing-to-models-zoo).

**Comment by Fissium** [comment]
Hi. I'm working on the implementation.

**Comment by AlekseySh** [comment]
@Fissium nice!
you can use "assigness" in the top right corner

**Comment by AlekseySh** [comment]
Done
