### ISSUE TITLE
Hugging Face `transformers` library integration

### ISSUE THREAD

**Issue by lamducanhndgv** [OML-Team/open-metric-learning#508]
Hi, is there any tutorial in training pipeline using Computer Vision models from [transformers](https://github.com/huggingface/transformers) library? If not, what are the steps to archive that? 

Thank you

**Comment by AlekseySh** [comment]
Hi!

There is no specific integration, but to use any external models:
* Follow the [instruction](https://github.com/OML-Team/open-metric-learning/tree/main/pipelines#how-to-use-my-own-implementation-of-loss-extractor-etc) to add your model to Pipelines (aka Config API)
* To work in [Python](https://github.com/OML-Team/open-metric-learning/tree/main?tab=readme-ov-file#examples) you only need to make your model a child of `IExtractor` (you only need to add `feat_dim` method)

Thank you for using OML!
