### ISSUE TITLE
Move more requirements to optional 

### ISSUE THREAD

**Issue by AlekseySh** [OML-Team/open-metric-learning#529]
It will make the library lighter and it will help users to avoid version conflicts. 
Another reason is not to install all computer vision and nlp libraries because a user may only need to work with one of the modalities. 

Good candidates to become optional:
```
torchvision
albumentations
opencv-python
tensorboard
pytorch-lightning + hydra (it may be tricky one)
```

I believe, we should make a dedicated PR for each particular requirement.

------
* OML reqs: https://github.com/OML-Team/open-metric-learning/blob/main/ci/requirements.txt
* OML optional reqs: https://github.com/OML-Team/open-metric-learning/blob/main/ci/requirements_optional.txt

See how we handle such requirements in tests: `pytest.mark.needs_optional_dependency`

**Comment by ayasyrev** [comment]
Hello! I'll do it!

**Comment by AlekseySh** [comment]
@ayasyrev that's great! I think we should separate work for each particular requirements (except for Lightning, because it goes altogether with Hydra)

Since you are Albumentations' contributor, you may start working on this requirement. What would you say?
