### ISSUE TITLE
Make an example of using OML for texts 

### ISSUE THREAD

**Issue by AlekseySh** [OML-Team/open-metric-learning#530]

**Comment by AlekseySh** [comment]
Here is @VSXV 's draft 
[link](https://colab.research.google.com/drive/1XwIYr74UjcUShAycbuZ5lcZJ06XNg2e-#scrollTo=DOCEONjb503k)

**Comment by VSXV** [comment]
Yep. I'll do that

**Comment by Fissium** [comment]
Hi. @VSXV You can also take a look at my example https://github.com/Fissium/metric-learning/blob/main/train_bert.py

**Comment by VSXV** [comment]
@Fissium great. Thank you!

**Comment by VSXV** [comment]
@AlekseySh 
Prepared two notebooks.
[With model training](https://colab.research.google.com/drive/1L5QQ8T3pQSltbnWi-QufuDtFbvWK6qNQ#scrollTo=RLvYAK6aCqOj)
[With validation two models: BERT base and trained one](https://colab.research.google.com/drive/1DqzaGkB__G6pu8JjTFojfHVlbw97oaxm#scrollTo=ejYf6AknCtn1)

If we want to have interactive ones, should add cloud file downloading.

**Comment by AlekseySh** [comment]
@VSXV yest, it would be cool

**Comment by AlekseySh** [comment]
as far as I remember the file is only about 5 mb

**Comment by VSXV** [comment]
I've added that. @AlekseySh

**Comment by AlekseySh** [comment]
The example will be merged with this PR: https://github.com/OML-Team/open-metric-learning/pull/557

**Comment by AlekseySh** [comment]
Finally done in OML 3.0.
Thanks everyone for contributions, including @Fissium and @VSXV
