### ISSUE TITLE
Add support for EVA-CLIP model

### ISSUE THREAD

**Issue by stoensin** [OML-Team/open-metric-learning#532]
Dear developers,

I would like to request the addition of support for the EVA-CLIP model in this project. EVA-CLIP is a powerful image-text dual-encoder model that has shown strong performance on a variety of visual tasks.

Including support for EVA-CLIP would be valuable for users who wish to leverage its capabilities for their own applications and research. The ability to easily integrate EVA-CLIP into this project would greatly expand its utility and functionality.

I would be happy to contribute to the development effort required to implement EVA-CLIP support, if that would be helpful. Please let me know if you have any questions or need further information from me.

Thank you for your consideration.
eva-clip:https://github.com/baaivision/EVA/tree/master/EVA-CLIP
Best regards
🤩

**Comment by AlekseySh** [comment]
Hi,

Thank you for your interest!

Does EVA-CLIP have any requirements different from what we have in OML? (You could check them in the `ci` folder of the repo).


Here is the recent PR where we added DINO v2 model. Just for reference. 
[PR](https://github.com/OML-Team/open-metric-learning/pull/519)

**Comment by AlekseySh** [comment]
Deu to inactivity
