### ISSUE TITLE
Memory bank with categories

### ISSUE THREAD

**Issue by DaloroAT** [OML-Team/open-metric-learning#61]
Memory bank can generate a lot of easy negatives. We need to find a way to use CategorySampler + CategoryMemoryBank.

Probably we can use MemoryBank as is, but modify the sampler (or create new one) so that it can generate several identical categories in a row. Possibly with the same labels.

**Comment by shikicool** [comment]
Hi,

**Comment by shikicool** [comment]
Hi,
Is it similar to **[XBM](https://github.com/msight-tech/research-xbm)**?
If true, that would be a great job in the OML :+1:

**Comment by AlekseySh** [comment]
Yes, there are two similar miners with memory, both are close to XBM, but the second one is more customizable.
* [TripletMinerWithMemory](https://open-metric-learning.readthedocs.io/en/latest/contents/miners.html#id3)
* [MinerWithBank](https://open-metric-learning.readthedocs.io/en/latest/contents/miners.html#minerwithbank)
