### ISSUE TITLE
Optimal batch size for triplet loss (hard batch mining)

### ISSUE THREAD

**Issue by sujit-dn** [OML-Team/open-metric-learning#626]
I am currently training triplet loss with n=2, l=2 with margin 0.5 on custom dataset. Training model with ViTs16  and linear classification layer as projector. Model is able to converge as can be seen from classification loss. However during test time inference no. of matches produced are not very high. Model still gets confused and produces correct pair match with less confidence. Does increasing batch size by training with l=16/32, n=4/8 will help here?
![vits16_graph_0 5_hard2](https://github.com/user-attachments/assets/79425155-037b-464d-aa7c-08eeefd6f94d)
![vits16_graph_0 5_hard](https://github.com/user-attachments/assets/a1720ca2-d0cf-4d00-9427-51617ade7c9b)

**Comment by AlekseySh** [comment]
hey, @sujit-dn  and thank you for your interest in OML!

I would say, bs=4 (n=2, l=2) is a kinda small. 
Do you have more memory on your GPU? 

I like setting batch size as this:
* set the number of instances per class in the batch equal to the median size of your class (it works well when it's about 4 or 5)
* set the number of classes in the batch as big as your GPU let you to set

**Comment by AlekseySh** [comment]
due to inactivity

**Comment by sujit-dn** [comment]
Hey @AlekseySh, We did trained model with semi hard triplet loss num labels =16, num instances per label=2. Found it did indeed improve overall performance of results (in terms of mAP and CMC score) as well as accuracy.

**Comment by AlekseySh** [comment]
@sujit-dn I'm glad to hear it. Have a nice day!
