### ISSUE TITLE
Metric learning without labels

### ISSUE THREAD

**Issue by JAVARSHA** [OML-Team/open-metric-learning#628]
Is there a way to finetune dinov2 using OML with an unlabelled dataset. Does OML support that? Also, how will the STIR finetuning take place. My aim is to finetune dinov2 on my dataset, and also finetune the STIR. But all of this with an unlabelled dataset

**Comment by JAVARSHA** [comment]
@AlekseySh @leoromanovich @b0nce @DaloroAT @dapladoc 

I want this finetuned model to generate embeddings. Not for classification

**Comment by AlekseySh** [comment]
Hey, @JAVARSHA 

We don't support unlabelled training in OML. I recommend you to find other solutions. You keywords are: Self Supervised Learning - SSL, Unsupervised Learning, Contrastive Learning. Check out this library: https://github.com/lightly-ai/lightly
