### ISSUE TITLE
Simplify args in readme examples

### ISSUE THREAD

**Issue by AlekseySh** [OML-Team/open-metric-learning#81]

**Comment by Rei-Moriaty** [comment]
Hi @AlekseySh 

This is my first time contributing to open source. I wanted to work on this. Can you give me a brief on what needs to be done?

**Comment by AlekseySh** [comment]
Sorry, this issue is outdated, but I answered your comment in the other issue: https://github.com/OML-Team/open-metric-learning/issues/108 
So, you can check it
